import bghome from "../assets/IMG-20240220-WA0005.webp";
import Footer from "./Components/Footer";
import Navbar from "./Components/Navbar";
import checklist from "../assets/checklist.png";

export default function Home() {
  return (
    <>
      <title>Home</title>
      <meta name="description" content="Generated by create-t3-app" />

      {/* // center phone */}
      <Navbar />
      {/* Section 1 */}
      <div
        style={{ "--image-url": `url(${bghome})` }}
        className="min-h-screen bg-[image:var(--image-url)] bg-cover bg-fixed bg-center bg-no-repeat text-center"
      >
        <div className="h-screen bg-black/50 backdrop-blur-none">
          <div className="md:bg-opacity-50 px-4 pt-72 md:flex md:flex-col md:items-center md:justify-center">
            <article className="prose lg:prose-xl text-center text-white">
              <h1 className="text-5xl font-bold text-white md:text-8xl">
                Kerja ke
                <span className="text-red-500">&nbsp;Jepang</span>
              </h1>
              <p className="indent-8">
                "Share Value, Membangun Manusia, Membangun Bangsa Indonesia"
              </p>
            </article>

            <div className="mt-8 flex justify-center">
              <button className="btn rounded bg-white px-6 py-2 font-semibold text-blue-700 hover:bg-gray-200">
                Daftar
              </button>
            </div>
          </div>
        </div>
      </div>
      {/* Section 2 */}
      <div className="flex min-h-screen flex-col items-center justify-center px-4">
        <p class="prose md:prose-2xl text-center md:text-2xl">
          <p className="text-4xl font-bold">
            Kerja ke
            <span className="font-bold text-red-500">&nbsp;Jepang</span>
          </p>
          <p className="text-justify indent-8">
            RPK Yaruki Solusi Indonesia adalah lemabaga pendidikan bahasa Jepang
            pengirim tenaga kerja ke Jepang.
          </p>
          <p className="text-justify indent-8">
            PT. Yaruki Solusi Indonesia ingin memfasilitasi anak bangsa untuk
            dapat berkembang dan membangun pengalaman guna mencapai mimpi masa
            depan yang lebih baik dengan progam :
          </p>
        </p>
        <div className="card bg-base-100 my-4 w-screen text-2xl shadow-sm md:my-0 md:w-3xl">
          <div className="card-body">
            <ul className="flex flex-col gap-2 text-lg font-bold md:text-xl">
              <li className="flex items-center gap-2">
                <img src={checklist} alt="checklist" className="w-8" />
                Magang (Jishusei)
              </li>
              <li className="flex items-center gap-2">
                <img src={checklist} alt="checklist" className="w-8" />
                SSW/TG (Spesified Skill Worker/ Tokutei Ginou)
              </li>
              <li className="flex items-center gap-2">
                <img src={checklist} alt="checklist" className="w-8" />
                Engineer
              </li>
              <li className="flex items-center gap-2">
                <img src={checklist} alt="checklist" className="w-8" />
                Kuliah Sambil Magang (Nihongo Gakkau)
              </li>
            </ul>
          </div>
        </div>
        <div className="pt-4 md:text-2xl">kenapa memilih LPK Yaruki?</div>
        <div className="card bg-base-100 my-4 w-screen shadow-sm md:my-0 md:w-3xl">
          <div className="card-body">
            <ul className="flex flex-col gap-2 text-lg font-bold md:text-xl">
              <li className="flex items-center gap-2">
                <img src={checklist} alt="checklist" className="w-8" />
                Support Dari Awal Hingga Akhir
              </li>
              <li className="flex items-center gap-2">
                <img src={checklist} alt="checklist" className="w-8" />
                Sistem Dana Talang
              </li>
              <li className="flex items-center gap-2">
                <img src={checklist} alt="checklist" className="w-8" />
                Memiliki Training Center (Group Bisnis)
              </li>
            </ul>
          </div>
        </div>
      </div>
      <Footer />
    </>
  );
}
